// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-BFsgf3FZn64JU2gJIxarhjygT0eOSTA',
    appId: '1:267125743362:web:d7d192a9e3e09b0914ac1b',
    messagingSenderId: '267125743362',
    projectId: 'post-app-9f733',
    authDomain: 'post-app-9f733.firebaseapp.com',
    storageBucket: 'post-app-9f733.firebasestorage.app',
    measurementId: 'G-RMTC2RJ7LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtX3C6xYMRRwW9Xoj1Ed6_3rlJ2OA6h0',
    appId: '1:267125743362:android:8a8a3362e6c9647d14ac1b',
    messagingSenderId: '267125743362',
    projectId: 'post-app-9f733',
    storageBucket: 'post-app-9f733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgOqofR-lk3rOAZPuo8G6j6-wwT19u_Qo',
    appId: '1:267125743362:ios:5e351c47f8e60d6314ac1b',
    messagingSenderId: '267125743362',
    projectId: 'post-app-9f733',
    storageBucket: 'post-app-9f733.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgOqofR-lk3rOAZPuo8G6j6-wwT19u_Qo',
    appId: '1:267125743362:ios:5e351c47f8e60d6314ac1b',
    messagingSenderId: '267125743362',
    projectId: 'post-app-9f733',
    storageBucket: 'post-app-9f733.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-BFsgf3FZn64JU2gJIxarhjygT0eOSTA',
    appId: '1:267125743362:web:c4e163abba80edd014ac1b',
    messagingSenderId: '267125743362',
    projectId: 'post-app-9f733',
    authDomain: 'post-app-9f733.firebaseapp.com',
    storageBucket: 'post-app-9f733.firebasestorage.app',
    measurementId: 'G-1L2N61E6R7',
  );
}
